import type { Metadata } from "next";
import { Suspense } from "react";

import { Providers } from "@/app/Providers";
import Header from "@/components/header/header";
//import { Inter } from "next/font/google";
import { Toaster } from "@/components/ui/toaster";

import "./globals.css";

//const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="h-screen w-screen">
        <Providers>
          <Header />
          <main className="flex-grow">
            <Suspense fallback={<div>Loading...</div>}>{children}</Suspense>
          </main>
          <Toaster />
        </Providers>
      </body>
    </html>
  );
}
